// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229102313_AddCodeAnalysis")]
    partial class AddCodeAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.CodeEdge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RepositorySnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositorySnapshotId")
                        .HasDatabaseName("idx_edge_snapshot");

                    b.HasIndex("SourceNodeId")
                        .HasDatabaseName("idx_edge_source");

                    b.HasIndex("TargetNodeId")
                        .HasDatabaseName("idx_edge_target");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_edge_type");

                    b.HasIndex("SourceNodeId", "TargetNodeId", "Type")
                        .HasDatabaseName("idx_edge_source_target_type");

                    b.ToTable("CodeEdges");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.CodeNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Accessibility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAbstract")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAsync")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExtensionMethod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RepositorySnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializedName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("idx_node_display_name");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("idx_node_normalized_name");

                    b.HasIndex("ParentNodeId")
                        .HasDatabaseName("idx_node_parent");

                    b.HasIndex("RepositorySnapshotId")
                        .HasDatabaseName("idx_node_snapshot");

                    b.HasIndex("SerializedName")
                        .HasDatabaseName("idx_node_serialized_name");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_node_type");

                    b.HasIndex("RepositorySnapshotId", "SerializedName")
                        .IsUnique()
                        .HasDatabaseName("idx_node_unique");

                    b.ToTable("CodeNodes");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.IndexedRepository", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("IndexingDuration")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferencesCollected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SymbolsCollected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("idx_indexed_repository_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_indexed_repository_status");

                    b.HasIndex("RepositoryId", "CommitSha")
                        .HasDatabaseName("idx_indexed_repository_commit");

                    b.ToTable("IndexedRepositories");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.IndexingError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFatal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("RepositorySnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("idx_error_file");

                    b.HasIndex("RepositorySnapshotId")
                        .HasDatabaseName("idx_error_snapshot");

                    b.ToTable("IndexingErrors");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.Occurrence", b =>
                {
                    b.Property<long>("ElementId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CodeEdgeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CodeNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ElementId", "SourceLocationId");

                    b.HasIndex("CodeEdgeId");

                    b.HasIndex("CodeNodeId");

                    b.HasIndex("ElementId")
                        .HasDatabaseName("idx_occurrence_element");

                    b.HasIndex("SourceLocationId")
                        .HasDatabaseName("idx_occurrence_location");

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.SourceFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("csharp");

                    b.Property<int?>("LineCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("RepositorySnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("idx_file_hash");

                    b.HasIndex("RepositorySnapshotId")
                        .HasDatabaseName("idx_file_snapshot");

                    b.HasIndex("RepositorySnapshotId", "Path")
                        .IsUnique()
                        .HasDatabaseName("idx_file_path");

                    b.ToTable("SourceFiles");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.SourceLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndOffset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("idx_source_location_file");

                    b.HasIndex("FileId", "StartLine", "StartColumn")
                        .HasDatabaseName("idx_source_location_position");

                    b.ToTable("SourceLocations");
                });

            modelBuilder.Entity("MyApp.Domain.Identity.FlowBranchPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreateLinkedBranches")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("FlowBranchPreferences", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Identity.GitHubOAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("GitHubOAuthStates", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Identity.UserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Observability.AuditTrailEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EventType", "OccurredAt");

                    b.ToTable("AuditTrailEntries", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.CodeEdge", b =>
                {
                    b.HasOne("MyApp.Domain.CodeAnalysis.IndexedRepository", "RepositorySnapshot")
                        .WithMany("Edges")
                        .HasForeignKey("RepositorySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyApp.Domain.CodeAnalysis.CodeNode", "SourceNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Domain.CodeAnalysis.CodeNode", "TargetNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositorySnapshot");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.CodeNode", b =>
                {
                    b.HasOne("MyApp.Domain.CodeAnalysis.CodeNode", "ParentNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyApp.Domain.CodeAnalysis.IndexedRepository", "RepositorySnapshot")
                        .WithMany("Nodes")
                        .HasForeignKey("RepositorySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentNode");

                    b.Navigation("RepositorySnapshot");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.IndexingError", b =>
                {
                    b.HasOne("MyApp.Domain.CodeAnalysis.SourceFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyApp.Domain.CodeAnalysis.IndexedRepository", "RepositorySnapshot")
                        .WithMany()
                        .HasForeignKey("RepositorySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("RepositorySnapshot");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.Occurrence", b =>
                {
                    b.HasOne("MyApp.Domain.CodeAnalysis.CodeEdge", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("CodeEdgeId");

                    b.HasOne("MyApp.Domain.CodeAnalysis.CodeNode", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("CodeNodeId");

                    b.HasOne("MyApp.Domain.CodeAnalysis.SourceLocation", "SourceLocation")
                        .WithMany("Occurrences")
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.SourceFile", b =>
                {
                    b.HasOne("MyApp.Domain.CodeAnalysis.IndexedRepository", "RepositorySnapshot")
                        .WithMany("Files")
                        .HasForeignKey("RepositorySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositorySnapshot");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.SourceLocation", b =>
                {
                    b.HasOne("MyApp.Domain.CodeAnalysis.SourceFile", "File")
                        .WithMany("SourceLocations")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.CodeEdge", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.CodeNode", b =>
                {
                    b.Navigation("ChildNodes");

                    b.Navigation("IncomingEdges");

                    b.Navigation("Occurrences");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.IndexedRepository", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Files");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.SourceFile", b =>
                {
                    b.Navigation("SourceLocations");
                });

            modelBuilder.Entity("MyApp.Domain.CodeAnalysis.SourceLocation", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
